name: 'Oie'
on:
  push:
    branches:
      - 'develop'
      - 'v2.[5-9].x-release'
      - 'v[3-9].*.x-release'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Installing test dependencies
        working-directory: ./bigbluebutton-tests/playwright
        run: |
          npm install
          npx playwright install
          npx playwright install-deps
          export NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/bbb-dev/bbb-dev-ca.crt"
          export ACTIONS_RUNNER_DEBUG="true"
      - name: Run tests
        env:
          BBB_URL: https://dev25.bigbluebutton.org/bigbluebutton/api
          BBB_SECRET: zPRyjPtHOoDcM75jFy2k1oeQXNEJCt0BEMdKjFZKo
        working-directory: ./bigbluebutton-tests/playwright
        run: npm test audio -- --project=chromium
      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dale
          path: bigbluebutton-tests/playwright/nao-existe.config.js
      - name: Upload settings file
        uses: actions/upload-artifact@v3
        with:
          name: tests-report
          path: bigbluebutton-tests/playwright/playwright-report
      - name: Get comment body
        id: get-comment-body
        run: |
          body="$(cat bigbluebutton-tests/playwright/.env.template)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          # body-includes: Build output
      - if: steps.fc.outputs.comment-id != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.fc.outputs.comment-id }}
            })
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: bigbluebutton-tests/playwright/playwright-report/index.html
      - name: PR Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Test link [clicking here](${{ steps.html_preview.outputs.url }})\n
            run link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}