name: 'Oie'
on:
  push:
    branches:
      - 'develop'
      - 'v2.[5-9].x-release'
      - 'v[3-9].*.x-release'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    steps:
      # - uses: actions/checkout@v2
      # - name: Installing test dependencies
      #   working-directory: ./bigbluebutton-tests/playwright
      #   run: |
      #     npm install
      #     npx playwright install
      #     npx playwright install-deps
      #     export NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/bbb-dev/bbb-dev-ca.crt"
      #     export ACTIONS_RUNNER_DEBUG="true"
      # - name: Run tests
      #   working-directory: ./bigbluebutton-tests/playwright
      #   run: npm test audio -- --project=chromium
      # - name: Forced failure
      #   run: |
      #     sudo sh -c '
      #     echo "failing..."
      #     exit 1
      #     '
      # - if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dale
      #     path: bigbluebutton-tests/playwright/nao-existe.config.js
    - name: Upload settings file
      uses: actions/upload-artifact@v3
      with:
        name: settings-file
        path: bigbluebutton-tests/playwright/.env.template
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: settings-file
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        # body-includes: Build output
    - if: steps.fc.outputs.comment-id != ''
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.deleteComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ steps.fc.outputs.comment-id }}
          })
    - id: get-comment-body
      run: |
        body="$(cat settings-file)"
    - name: PR Comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Test:
          ${{ steps.get-comment-body.outputs.body }}
    # - name: HTML Preview
    #   id: html_preview
    #   uses: pavi2410/html-preview-action@v2
    #   with:
    #     html_file: 'index.html'